AllCops:
  Exclude:
    - "lib/**/*"
    - "bin/**/*"
    - vendor/**/*.rb
Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
Metrics/MethodLength:
  Exclude:
    - db/migrate/20240203050618_devise_create_users.rb
Metrics/BlockLength:
  Exclude: 
    - config/environments/development.rb
Metrics/ClassAndModuleChildren:
  Exclude:
    - test/channels/application_cable/connection_test.rb
Lint/UnderscorePrefixedVariableName:
  Exclude:
    - app/controllers/users/sessions_controller.rb
Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
